### ISSUE TITLE
newgc: 0x00000000004426d5 in atomic_visit_ephemerons (g=0x40000840) at lj_gc.c:876

### ISSUE THREAD

**Issue by CapsAdmin** [corsix/LuaJIT#1]
compiled with `gcc 5.4.0` on `x64 linux` with the flags `LUA_USE_ASSERT`, `CCDEBUG=-g` and `CCOPT=-fomit-frame-pointer`

```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004426d5 in atomic_visit_ephemerons (g=0x40000840) at lj_gc.c:876
876         GCtab *t = gco2tab(gcref(weak[wi]));
(gdb) bt
#0  0x00000000004426d5 in atomic_visit_ephemerons (g=0x40000840) at lj_gc.c:876
#1  0x0000000000443187 in lj_gc_atomic (g=0x40000840, L=0x40000800) at lj_gc.c:1024
#2  0x0000000000445009 in gc_onestep (L=0x40000800) at lj_gc.c:1441
#3  0x0000000000445fde in lj_gc_step (L=0x40000800) at lj_gc.c:1692
#4  0x000000000043e5bd in lj_fff_gcstep ()
#5  0x0000000000419e70 in lua_pcall (L=0x40000800, nargs=0, nresults=-1, errfunc=2) at lj_api.c:1057
#6  0x00000000004042de in docall (L=0x40000800, narg=0, clear=0) at luajit.c:121
#7  0x0000000000404c7d in handle_script (L=0x40000800, argx=0x7fffffffde50) at luajit.c:291
#8  0x0000000000405991 in pmain (L=0x40000800) at luajit.c:551
#9  0x000000000043cca2 in lj_BC_FUNCC ()
#10 0x000000000041a102 in lua_cpcall (L=0x40000800, func=0x4057b1 <pmain>, ud=0x0) at lj_api.c:1081
#11 0x0000000000405aa1 in main (argc=2, argv=0x7fffffffde48) at luajit.c:580
```

Reproducing this is difficult as isolating the code where this happens makes it not crash. In my code it seems to happen at the same place when jit is off but when it's on it can be in random places.

**Comment by corsix** [comment]
e796e0b fixes something which _might_ cause this

**Comment by CapsAdmin** [comment]
I think that fixed it.
