### ISSUE TITLE
newgc: crash when allocating more than 129016 bytes with ffi.new

### ISSUE THREAD

**Issue by CapsAdmin** [corsix/LuaJIT#2]
compiled with `gcc 5.4.0` on `x64 linux` with the flags `LUA_USE_ASSERT`, `CCDEBUG=-g` and `CCOPT=-fomit-frame-pointer`

happens without jit as well

to reproduce
`luajit -e "require('ffi').new('uint8_t[?]', 129016 + 1)"`

using gdb though the limit seems to increase to 262432 + 1

```
Starting program: /media/caps/ssd_840_120gb/goluwa/data/bin/linux_x64/luajit_corsix-newgc_debug-assert -e require\(\"ffi\"\).new\(\"uint8_t\[\?\]\",\ 262432\ +\ 1\)
luajit_corsix-newgc_debug-assert: lj_obj.h:968: setgcV: Assertion `!((((o)->it) - ((~4u)+1)) > ((~13u) - ((~4u)+1))) || lj_gc_checklive(L, (((GCobj *)(uintptr_t)((o)->gcr).gcptr32)), ((o)->it))' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7320418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7320418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff732201a in __GI_abort () at abort.c:89
#2  0x00007ffff7318bd7 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x4d7200 "!((((o)->it) - ((~4u)+1)) > ((~13u) - ((~4u)+1))) || lj_gc_checklive(L, (((GCobj *)(uintptr_t)((o)->gcr).gcptr32)), ((o)->it))", file=file@entry=0x4d70da "lj_obj.h", line=line@entry=968, function=function@entry=0x4d787c <__PRETTY_FUNCTION__.4109> "setgcV") at assert.c:92
#3  0x00007ffff7318c82 in __GI___assert_fail (assertion=0x4d7200 "!((((o)->it) - ((~4u)+1)) > ((~13u) - ((~4u)+1))) || lj_gc_checklive(L, (((GCobj *)(uintptr_t)((o)->gcr).gcptr32)), ((o)->it))", file=0x4d70da "lj_obj.h", line=968, function=0x4d787c <__PRETTY_FUNCTION__.4109> "setgcV") at assert.c:101
#4  0x0000000000437a3f in setgcV (it=4294967285, v=0x4001fed4, o=0x4001fed0, L=0x40000800) at lj_obj.h:968
#5  setcdataV (v=0x4001fed4, o=0x4001fed0, L=0x40000800) at lj_obj.h:980
#6  lj_cf_ffi_new (L=0x40000800) at lib_ffi.c:509
#7  0x000000000043cca2 in lj_BC_FUNCC ()
#8  0x0000000000419e70 in lua_pcall (L=0x40000800, nargs=0, nresults=0, errfunc=2) at lj_api.c:1057
#9  0x00000000004042de in docall (L=0x40000800, narg=0, clear=1) at luajit.c:121
#10 0x000000000040460b in dostring (L=0x40000800, s=0x7fffffffe142 "require(\"ffi\").new(\"uint8_t[?]\", 262432 + 1)", name=0x4cf3dd "=(command line)") at luajit.c:174
#11 0x0000000000405577 in runargs (L=0x40000800, argv=0x7fffffffdd58, argn=3) at luajit.c:457
#12 0x000000000040593d in pmain (L=0x40000800) at luajit.c:547
#13 0x000000000043cca2 in lj_BC_FUNCC ()
#14 0x000000000041a102 in lua_cpcall (L=0x40000800, func=0x4057b1 <pmain>, ud=0x0) at lj_api.c:1081
#15 0x0000000000405aa1 in main (argc=3, argv=0x7fffffffdd58) at luajit.c:580
```

**Comment by corsix** [comment]
Well that was never going to work. Fixed in adfa7502 (and test in https://github.com/LuaJIT/LuaJIT-test-cleanup/commit/7897e7fff3f04e65838c316ee9caf27f78e9f76b).
